### ISSUE TITLE
Solution(X) returns false. Shouldn't it return true?

### ISSUE THREAD

**Issue by kaushal-py** [benbotto/prolog-einstein-solver#1]
When I execute the command `swipl einstein.pl`, I get the following output.
```
?- solution(X).
X = [[norwegian, water, dunhill, yellow, cats], [dane, tea, blends, blue, horse], [brit, milk, pall_mall, red, birds], [german, coffee, prince, green, fish], [swede, beer, bluemasters, white|...]] [write]
X = [[norwegian, water, dunhill, yellow, cats], [dane, tea, blends, blue, horse], [brit, milk, pall_mall, red, birds], [german, coffee, prince, green, fish], [swede, beer, bluemasters, white, dogs]] ;

false.
````

Why is the output returning false? How do I make it return a true value?

**Comment by benbotto** [comment]
Hi @kb-studios,

It should not return true, no.  After printing the solution, prolog tries to query for another solution and can't find one (there's only one solution), so it prints false.  That's the short of it, but there are more details in this SO question: https://stackoverflow.com/questions/28182825/predicate-prints-out-unexpected-false  In the SO question, the `likes` predicate is analogous to my `neighbor` predicate.

[b]
